spring:
  datasource: #DB ??? ?? ??? 8080 ??? mysql?? ???? ??? 3306
    url: jdbc:mysql://localhost:3306/student_lecture
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
    open-in-view: false

