spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_lecture
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  #@Entity? ??? ???? ???? ?? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
    open-in-view: false